
- name: install bash and curl to get nodejs
  apt: 
    pkg: 
      - bash
      - curl

- name: get nodejs repo
  shell: 'curl -sLS https://deb.nodesource.com/setup_{{ node_version }}.x | bash -'

- name: install apt packages
  apt:
    pkg:
      - nodejs
      - sudo
      - unzip
    update_cache: yes

- name: globally install npm
  npm:
    name: npm
    global: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

